# Generated by Django 3.1.6 on 2021-02-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tickers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to='trends.tickers')),
            ],
        ),
    ]
